---
swagger: '2.0'
info:
  title: Battery
  version: 0.9
  license:
    name: Angaza Data Model License (MIT License)
    url: https://github.com/angaza/nexus-embedded/blob/master/LICENSE
    x-copyright: Copyright 2020 Angaza, Inc. All rights reserved
schemes:
  - coap
consumes:
  # Note: JSON provided to render examples using redoc, actual data transmitted
  # is `application/vnd.ocf+cbor`
  #- application/vnd.ocf+cbor
  - application/json
produces:
  #- application/vnd.ocf+cbor
  - application/json
paths:
  "/batt":  # suggested URI
    get:
      summary: Retrieve current battery status
      description: |
        This Resource describes the attributes associated with a battery, and
        allows authorized devices (authorized via a separate system, e.g.
        full Nexus Channel security) to update the battery 'low state of charge'
        threshold, if available.

        The minimum set of properties to implement are `cp` (charge percentage)
        and `vb` (battery voltage).

        Example `GET` response body in CBOR:
          `BF627662192D73626370183262746814626361197D00626473F5626367F5626C62F5626674F462737304FF`

        Adapted from OCF spec [`oic.r.energy.battery`](https://www.oneiota.org/revisions/6148)
      parameters:
        # - "$ref": "#/parameters/interface"
      responses:
        '205':
          description: ''
          x-example:
            vb: 11635
            cp: 50
            th: 20
            ca: 32000
            ds: true
            cg: true
            lb: true
            ft: false
            ss: 4
          schema:
            "$ref": "#/definitions/Battery"
    post:
      summary: 'Update battery low state-of-charge threshold'
      description: |
        Update battery threshold (th) if supported.

        Example `POST` request payload in CBOR:
          `BF62746814FF`
      parameters:
        # - "$ref": "#/parameters/interface"
      - name: body
        in: body
        required: true
        schema:
          "$ref": "#/definitions/BatteryUpdate"
        x-example:
          th: 20
      responses:
        '204':
          description: ''
          x-example:
            th: 20
          schema:
            "$ref": "#/definitions/BatteryUpdate"
        '400':
          description: Provided payload was not understood or ill-formatted.
        '403':
          description: Requester not authorized to update threshold.

# Query parameters optional, Channel Core does not require interface query support
parameters:
  interface:
    in: query
    name: if
    type: string
    enum:
    - oic.if.rw
    - oic.if.baseline
definitions:
  Battery:
    properties:
      rt:
        description: |
          **Fixed Specification Value Only**. The Resource Type
          (Only reported if `oic.if.baseline` interface query is supported)
        items:
          enum:
          - angaza.com.nx.battery
          maxLength: 64
          type: string
        minItems: 1
        uniqueItems: true
        readOnly: true
        type: array
        x-internal: true
      rtr:
        description: |
          **Fixed Specification Value Only**. The Nexus Channel Core Resource
          Type Registry value (Only reported if `oic.if.baseline` interface
          query is supported)
        readOnly: true
        type: integer
        minimum: 101
        maximum: 101
      if:
        description: |
          **Fixed Specification Value Only**. The OCF Interface set
          supported by this Resource. (Only reported if `oic.if.baseline`
          interface query is supported)
        items:
          enum:
          - oic.if.rw  # oic.if.baseline optional
          type: string
        minItems: 1
        uniqueItems: true
        readOnly: true
        type: array
        x-internal: true
      vb:
        description: The current voltage of the battery in millivolts.
        readOnly: true
        type: integer
        format: uint32
        example: 11635
      ib:
        description: The current charging or discharge current milliamps
        readOnly: true
        type: integer
        format: uint32
        example: 1000
      cp:
        description: The current charge percentage (state-of-charge).
        maximum: 100
        minimum: 0
        readOnly: true
        type: integer
        format: uint
        example: 50
      cs:
        description: >
            Charging state, Sort order:
             * `0` - No Data
             * `1` - Charging, fast
             * `2` - Charging, slow / trickle
             * `3` - Discharging
        readOnly: true
        schema:
            type: integer
            enum: [0, 1, 2, 3]
      th:
        description: The threshold percentage for the low battery warning.
          When battery capacity in percent (`cp`) drops below this value, the
          `lb` (low battery) warning will turn 'true'.
        maximum: 100
        minimum: 0
        type: integer
        format: uint
        example: 20
      ca:
        description: The total capacity in milliAmp-hours (mAh).
        readOnly: true
        type: integer
        format: uint
        example: 32000
      ds:
        description: True if discharging, false otherwise.
        readOnly: true
        type: boolean
      cg:
        description: True if battery is charging, else false.
        readOnly: true
        type: boolean
      lb:
        description: Status of the low battery warning based upon the threshold
          defined by `th`.
        readOnly: true
        type: boolean
      ft:
        description: True if battery defect or fault detected.
        readOnly: true
        type: boolean
        example: false
      ss:
        description: Seconds since the observed data in this resource was
          measured.
        minimum: 0
        readOnly: true
        type: integer
        format: uint
        example: 4
      bh:
        description: Only for Battery Device, Could be Infrequently reported
        readOnly: true
        type: integer
        format: uint8
        example: 255
      cmin:
        description: Last Charge Cycle Minimum Battery Percentage
        readOnly: true
        type: integer
        format: uint16
        example: 25 
      cmax:
        description: Last Charge Cycle Maximum Battery Percentage
        readOnly: true
        type: integer
        format: uint16
        example: 85 
      tc:
        description: Last Charge Cycle charge time in minutes
        readOnly: true
        type: integer
        format: uint16
        example: 180 
      qc:
        description: Last Charge Cycle charge units in mAh
        readOnly: true
        type: integer
        format: uint16
        example: 1800
      pms:
        description: >
            Battery power management control, encoded for security, similar to a PAYG token, Sort order:
             * `0xXXXXXXXX` - Battery Power management is ON
             * `0xBA1234CA` - or another code manufacturer decides - Battery Power management switch to OFF (Idle for battery draining during battery calibration)
             * `0xBA1234DA` - or another code manufacturer decides - Battery Power management switched OFF
        readOnly: true
        schema:
            type: integer
            enum: [0xXXXXXXXX, 0xBA1234CA, 0xBA1234DA]
        readOnly: false
        type: integer
        format: uint32
        example: 0xBA1234CA 
      ts:
        description: Timestamp of recorded data in Unix format
        readOnly: true
        type: integer
        format: uint32
      ths: 
        description: Any resource with one or more timeseries properties is enabled with this optional property which can indicate that the device has stored historical data while offline that it can sequentially upload to the gateway via multiple reads
        readOnly: true
        type: integer
        format: uint16
        example: 10
      thi:
        description: Whenever this property is available that means it is a timeseries resource. thi = 0, means there is no more timeseries data. Any number greater than zero can be used for indicating which data proceeds especially when the timestamp is the same.
        readOnly: true
        type: integer
        format: uint32
        example: 2
    type: object
    required:
    - cp  # charge percentage
    - vb  # battery voltage
  BatteryUpdate:
    properties:
      th:
        description: The threshold percentage for the low battery warning.
        maximum: 100
        minimum: 0
        type: integer
        example: 20
      pms:
        description: >
            Battery power management control, encoded for security, similar to a PAYG token, Sort order:
             * `0xXXXXXXXX` - Battery Power management is ON
             * `0xBA1234CA` - or another code manufacturer decides - Battery Power management switch to OFF (Idle for battery draining during battery calibration)
             * `0xBA1234DA` - or another code manufacturer decides - Battery Power management switched OFF
        readOnly: true
        schema:
            type: integer
            enum: [0xXXXXXXXX, 0xBA1234CA, 0xBA1234DA]
        readOnly: false
        type: integer
        format: uint32
        example: 0xBA1234CA 

    type: object
    required:
    - th
