---
swagger: '2.0'
info:
  title: Temperature
  version: 'v0.9'
  license:
    name: Angaza Nexus Data Model License (MIT License)
    url: 'https://github.com/angaza/nexus-embedded/blob/master/LICENSE'
    x-copyright: 'Copyright 2021 Angaza, Inc. All rights reserved.'
schemes:
  - coap
consumes:
  # Note: JSON provided to render examples using redoc, actual data transmitted
  # is `application/vnd.ocf+cbor`
  #- application/vnd.ocf+cbor
  - application/json
produces:
  # - application/vnd.ocf+cbor
  - application/json

paths:
  /nx/temp:
    get:
      summary: Get current temperature and/or history and limits
      description: |-
        This resource indicates the temperature of or measured by a specific device. 

        See also -
        * angaza.com.nexus.channel.link_handshake - Information on Nexus channel link handshakes
          
      parameters:
        # - $ref: '#/parameters/interface'
      responses:
        200:
          description: "Temperature information from this device."
          schema:
            $ref: '#/definitions/temp'
          x-example:
            description: "x-example"
            temp: 25
            tmax: 32
            tmin: 22

    post:
      summary: Set operating temperature limits for the device
      description: |
        Sets the high and low temperature limits. If the endpoint
        determines that the requesting device is not authorized to control
        this device, an error response will be returned.
      parameters:
        - in: body
          name: Set Temperature limits
          description: Temperature limits
          schema:
            $ref: "#/definitions/temp"

      responses:
        200:
          description: Successfully updated limits
          schema:
              properties:
                re:
                  $ref: '#/definitions/temp/properties/temp'
        401:
          description: Client is not authorized to perform this action (client may lack a Nexus Channel Link to this device)

parameters:
  interface:
    in: query
    name: if
    type: string
    enum:
      - oic.if.rw
      - oic.if.baseline

definitions:
  temp:
    type: object
    properties:
      rt:
        description: |
          **Fixed Specification Value Only**. The Resource Type
          (Only reported if `oic.if.baseline` interface query is supported)
        items:
          enum:
          - angaza.com.nexus.core.environmental.temp
          maxLength: 64
          type: string
        minItems: 1
        uniqueItems: true
        readOnly: true
        type: array
        x-internal: true
      rtr:
        description: |
          **Fixed Specification Value Only**. The Nexus Channel Core Resource
          Type Registry value (Only reported if `oic.if.baseline` interface
          query is supported)
        readOnly: true
        type: integer
        minimum: 401
        maximum: 401
      if:
        description: |
          **Fixed Specification Value Only**. The OCF Interface set
          supported by this Resource. (Only reported if `oic.if.baseline`
          interface query is supported)
        items:
            enum:
            - oic.if.rw  # oic.if.baseline optional
            type: string
        minItems: 1
        uniqueItems: true
        readOnly: true
        type: array
        x-internal: true
      temp:
        description: temperature
        type: integer
        format: uint32_t
        readOnly: true
      tmax:
        description: max temperature since last reading
        type: integer
        format: uint32_t
        readOnly: true
      tmin:
        description: min temperature since last reading
        type: integer
        format: uint32_t
        readOnly: true
      hlim:
        description: Upper operating temperature limit
        type: integer
        format: uint32_t
        readOnly: false
      llim:
        description: Lower operating temperature limit
        type: integer
        format: uint32_t
        readOnly: false
      ts:
        description: Timestamp of recorded data in Unix format
        readOnly: true
        type: integer
        format: uint32
      tsh: 
        description: Any resource with one or more timeseries properties is enabled with this optional property which can indicate that the device has stored historical data while offline that it can sequentially upload to the gateway via multiple reads
        readOnly: true
        type: integer
        format: uint16
        example: 10
      thi:
        description: Whenever this property is available that means it is a timeseries resource. thi = 0, means there is no more timeseries data. Any number greater than zero can be used for indicating which data proceeds especially when the timestamp is the same.
        readOnly: true
        type: integer
        format: uint32
        example: 2
    required:
      - re
      - un
